[variables]
NIXPACKS_NO_AUTO_INSTALL = "true"

[phases.setup]
nixPkgs = [
  "python312", 
  "python312Packages.pip", 
  "python312Packages.lightgbm", 
  "python312Packages.shap", 
  "python312Packages.fastapi", 
  "python312Packages.uvicorn", 
  "python312Packages.sqlalchemy", 
  "python312Packages.psycopg2", 
  "python312Packages.pandas", 
  "python312Packages.numpy", 
  "python312Packages.requests"
]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  "source /opt/venv/bin/activate",
  "pip install --no-cache-dir -r requirements.txt"
]

# Default process to run
[start]
cmd = "source /opt/venv/bin/activate && cd /app/service-scoring && uvicorn main:app --host 0.0.0.0 --port $PORT"
stopTimeout = 5
