[variables]
NIXPACKS_NO_AUTO_INSTALL = "true"
PYTHONPATH = "/app"

[phases.setup]
nixPkgs = [
  "python312", 
  "python312Packages.pip", 
  "python312Packages.lightgbm", 
  "python312Packages.shap", 
  "python312Packages.fastapi", 
  "python312Packages.uvicorn", 
  "python312Packages.sqlalchemy", 
  "python312Packages.psycopg2", 
  "python312Packages.pandas", 
  "python312Packages.numpy", 
  "python312Packages.requests"
]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  "source /opt/venv/bin/activate",
  "pip install --no-cache-dir -r requirements.txt"
]

# Diagnostic command to run before startup
[processes.diagnostic]
cmd = "ls -la /app && echo 'PYTHON PATH:' && python -c 'import sys; print(sys.path)' && echo 'ENV:' && env | grep PYTHON && python /app/debug_path.py"

# Default process to run
[processes.web]
cmd = "source /opt/venv/bin/activate && python /app/debug_path.py && python -m uvicorn service_scoring.main:app --host 0.0.0.0 --port $PORT"

[processes.cron]
cmd = "source /opt/venv/bin/activate && python /app/debug_path.py && python -m service_cron.worker"

[processes.trainer]
cmd = "source /opt/venv/bin/activate && python /app/debug_path.py && python -m service_trainer.train"
