[variables]
NIXPACKS_NO_AUTO_INSTALL = "true"

[phases.setup]
nixPkgs = [
  "python312", 
  "python312Packages.pip", 
  "python312Packages.lightgbm", 
  "python312Packages.shap", 
  "python312Packages.fastapi", 
  "python312Packages.uvicorn", 
  "python312Packages.sqlalchemy", 
  "python312Packages.psycopg2", 
  "python312Packages.pandas", 
  "python312Packages.numpy", 
  "python312Packages.requests"
]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  "source /opt/venv/bin/activate",
  "pip install --no-cache-dir -r requirements.txt"
]

# Define the different processes
[processes.scoring]
cmd = "source /opt/venv/bin/activate && cd $NIXPACKS_APP_DIR && cd service-scoring && uvicorn main:app --host 0.0.0.0 --port $PORT"
stopTimeout = 5
restartPolicy = "ON_FAILURE"

[processes.cron]
cmd = "source /opt/venv/bin/activate && cd $NIXPACKS_APP_DIR && python -m service-cron.worker"
stopTimeout = 5
restartPolicy = "ON_FAILURE"

[processes.trainer]
cmd = "source /opt/venv/bin/activate && cd $NIXPACKS_APP_DIR && python -m service-trainer.train"
stopTimeout = 5
restartPolicy = "ON_FAILURE"

# Default process to run
[start]
cmd = "source /opt/venv/bin/activate && cd $NIXPACKS_APP_DIR && cd service-scoring && uvicorn main:app --host 0.0.0.0 --port $PORT"
stopTimeout = 5
